[cerebrium]
project = "p-eb5117e7"

[cerebrium.deployment]
name = "ml-classifier"
python_version = "3.12"
include = [
    "main.py",
    "src/",
    "model_artifacts/",
    "sample_images/",
    "tests/",
    "requirements.txt",
    "Dockerfile",
    "README.md"
]
exclude = [
    ".*",
    "__pycache__/**/*",
    "*.pyc",
    "**/__pycache__/**/*",
    "**/*.pyc",
    "**/venv/**/*",
    "**/env/**/*",
    ".git/**/*",
    ".pytest_cache/**/*",
    "*.log",
    "test_results/**/*"
]
shell_commands = []

[cerebrium.hardware]
cpu = 2
memory = 4.0
compute = "CPU"
gpu_count = 0
provider = "aws"
region = "us-east-1"

[cerebrium.runtime]
type = "custom"

[cerebrium.runtime.custom]
port = 8192
healthcheck_endpoint = "/health"
dockerfile_path = "./Dockerfile"

[cerebrium.scaling]
min_replicas = 0
max_replicas = 3
cooldown = 60
replica_concurrency = 10
